variables:
  IMAGE_NAME: cyberslot/app-repo
  IMAGE_TAG: python-app-1.0

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.9-slim-buster
  # image: python:3.11-slim-buster
  before_script:
    # - apt-get update && apt-get install make
    - apt update && apt install make
  script:
    - make test
  artifacts:
    paths:
      - src/script.sh

build_image:
  stage: build
  # image: docker:20.10.16
  image: docker:20.10.21
  services:
    # - docker:20.10.16-dind
    - docker:20.10.21-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGITSRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  # image: ruby:alpine3.16
  before_script:
    # - cat << EOF > script.sh
    #   if [ "$(docker ps -q)" != "" ]; then
    #     docker stop $(docker ps -q) && docker rm $(docker ps -aq)
    #   else
    #     docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG
    #   fi
    #   EOF
    # - chmod 700 $script
    - chmod 400 $SSH_KEY
  script:
    - scp -o StrictHostKeyChecking=no src/script.sh root@10.133.108.111:/root
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@10.133.108.111 "
        docker login -u $REGISTRY_USER -p $REGITSRY_PASS &&
        chmod 700 script.sh && 
        . script.sh"
        # docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"
        
        

        