# Multiple triggers
trigger:
  - main

schedules:
  - cron: "0 0 * * *"
    displayName: Deploy to dev env
    # Concurrency control
    batch: true
    branches:
      include:
        - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: deploymentDefaultLocation
    value: west-europe

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install azure-cli

  - script: |
      az login --service-principal --username $(CLIENT_ID) --password $(CLIENT_SECRET) --tenant $(TENANT_ID)
      az deployment sub create --location $(deploymentDefaultLocation) --template-file $(System.DefaultWorkingDirectory)/path/to/webapp.bicep --parameters $(System.DefaultWorkingDirectory)/path/to/params.json

  - task: PowerShell@2
    displayName: "Run PSRules Script"
    inputs:
      ## Inline PSRules script
      # targetType: "inline"
      # script: |
      #   # Add PSRules script here
      ## Referenced PSRules script
      targetType: "filePath"
      filePath: "path/to/psRulesScript.ps1"
