apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: webapp
  annotations: {}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: webapp
